"""Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from urllib.parse import parse_qsl, urlparse

import environ

from boutique.media import build_storages

BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent

env = environ.Env()
env_file = ROOT_DIR / ".env"
if env_file.exists():
    env.read_env(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG")

FRONTEND_URL = env.str("FRONTEND_URL")
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS")

APPEND_SLASH = env.bool("DJANGO_APPEND_SLASH")

if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]

SITE_ID = 1

# CorsMiddleware is installed below. Without an explicit allow-list it permits
# nothing, so every cross-origin request from the Next app is refused.
#
# In practice the browser talks to the Next BFF (same-origin) and Next talks to
# Django server-to-server, where CORS does not apply. This exists for the direct
# browser -> Django calls that remain, and for local development.
_cors_origins = env.str("CORS_ALLOWED_ORIGINS", default="")
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()] or [FRONTEND_URL]
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "ninja_extra",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
    "apps.boutiques",
    "apps.users",
    "apps.products",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # Serves the Django admin's own static files. Must sit directly after
    # SecurityMiddleware and before everything else.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "boutique.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "boutique.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db = urlparse(env.str("DATABASE_URL"))

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _db.path.lstrip("/"),
        "USER": _db.username,
        "PASSWORD": _db.password,
        "HOST": _db.hostname,
        "PORT": _db.port or 5432,
        "OPTIONS": dict(parse_qsl(_db.query)),
        # Neon's pooled endpoint is PgBouncer in transaction mode. A pooled
        # connection is handed back after every transaction, so a persistent
        # connection is not ours to keep.
        "CONN_MAX_AGE": 0,
    }
}

# Server-side cursors do not survive transaction pooling: PgBouncer returns the
# server connection to the pool at COMMIT, orphaning the cursor, and the next
# fetch fails with InvalidCursorName. QuerySet.iterator() opens one by default.
#
# The failure only appears against the pooler, so it cannot reproduce locally
# and no test will catch it. Materialise ids with list(...) before iterating.
DISABLE_SERVER_SIDE_CURSORS = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Login is by email (USERNAME_FIELD), so Django's default backend suffices for now.
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # default in Django's global_settings.py, duplicated here for clarity
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = build_storages(env)

# Behind Render's proxy, every request arrives over plain HTTP with the original
# scheme in this header. Without it Django believes the connection is insecure,
# builds `http://` absolute URLs, and refuses to set secure cookies.
#
# This is only safe because the proxy always overwrites the header. Trusting it
# from a directly reachable origin would let any client claim HTTPS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 1 hour to start. Raise it deliberately, after confirming every subdomain
    # serves HTTPS — HSTS is not reversible within its own max-age.
    SECURE_HSTS_SECONDS = 3600

AUTH_USER_MODEL = "users.User"


# JSON Web Tokens (django-ninja-jwt)
# Lifetimes are aligned with the frontend auth cookie maxAge (frontend/src/lib/auth.ts).
# The Next BFF refreshes on 401, so rotation is safe: each /auth/refresh mints a
# new refresh token and blacklists the old one (single-use). Login keys off
# USERNAME_FIELD (email) via the default ninja_jwt schema — no custom input schema.
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# Email (password recovery). Defaults to the console backend for local dev; set
# EMAIL_BACKEND to the SMTP backend and fill the credentials in .env to send for
# real. Mailpit (compose.yaml) receives on localhost:1025 with no auth.
EMAIL_BACKEND = env.str("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env.str("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="Zita Boutique <no-reply@amedeyo.com>")

# Unset, smtplib blocks ~130s on a dropped SYN. Mail is sent in the request
# (ADR-0012) and gunicorn's --timeout does not bound one. engineering-notes.md.
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=10)


# Celery — offloads the SMTP send so /auth/password/reset-request returns
# immediately. Broker is Redis. Set CELERY_TASK_ALWAYS_EAGER=True to run tasks
# inline (no broker/worker needed) for local dev or tests.
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TIME_ZONE
